-- KPROXY-GO schema init
-- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/zcdwccdgmpbwzccyfeno/sql/new

-- Tables
CREATE SEQUENCE IF NOT EXISTS go_campaigns_id_seq;
CREATE TABLE IF NOT EXISTS go_campaigns (
  id bigint NOT NULL DEFAULT nextval('go_campaigns_id_seq'),
  go_code text NOT NULL UNIQUE,
  category text NOT NULL CHECK (category = ANY (ARRAY['POCA_SET','ALBUM','RESTOCK'])),
  idol_name text NOT NULL,
  album text NOT NULL,
  version text,
  retail_store text,
  url text,
  set_price_krw numeric,
  retail_price_krw numeric,
  discount_pct numeric,
  pob_store text,
  pob_detail text,
  set_detail text,
  detail text,
  deadline date,
  is_closed boolean NOT NULL DEFAULT false,
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS go_buyer_orders_id_seq;
CREATE TABLE IF NOT EXISTS go_buyer_orders (
  id bigint NOT NULL DEFAULT nextval('go_buyer_orders_id_seq'),
  alibaba_username text NOT NULL,
  contact_email text,
  contact_note text,
  total_krw numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'submitted' CHECK (status = ANY (ARRAY['submitted','confirmed','shipped','cancelled'])),
  notified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS go_buyer_order_items_id_seq;
CREATE TABLE IF NOT EXISTS go_buyer_order_items (
  id bigint NOT NULL DEFAULT nextval('go_buyer_order_items_id_seq'),
  order_id bigint NOT NULL,
  go_code text NOT NULL,
  qty integer NOT NULL CHECK (qty > 0),
  unit_price_krw numeric,
  line_total_krw numeric,
  PRIMARY KEY (id),
  FOREIGN KEY (order_id) REFERENCES go_buyer_orders(id)
);

CREATE SEQUENCE IF NOT EXISTS cron_runs_id_seq;
CREATE TABLE IF NOT EXISTS cron_runs (
  id bigint NOT NULL DEFAULT nextval('cron_runs_id_seq'),
  job text NOT NULL,
  scope text NOT NULL,
  ran_at timestamptz NOT NULL DEFAULT now(),
  result jsonb,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS kakao_token (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  access_token text,
  refresh_token text,
  access_expires_at timestamptz,
  refresh_expires_at timestamptz,
  scope text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
INSERT INTO kakao_token (id) VALUES (1) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location text DEFAULT '',
  idol text DEFAULT '',
  album text DEFAULT '',
  version text DEFAULT '',
  member text DEFAULT '',
  barcode text DEFAULT '',
  weight numeric DEFAULT 0,
  stock_kr integer DEFAULT 0,
  stock_tw integer DEFAULT 0,
  safety_stock integer DEFAULT 5,
  safety_stock_tw integer DEFAULT 3,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Pop Up events + products (independent of GO campaigns)
CREATE SEQUENCE IF NOT EXISTS popup_events_id_seq;
CREATE TABLE IF NOT EXISTS popup_events (
  id          bigint NOT NULL DEFAULT nextval('popup_events_id_seq'),
  title       text   NOT NULL,
  group_name  text   NOT NULL,
  start_date  date,
  end_date    date,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS popup_events_active_idx ON popup_events (is_active, end_date);

CREATE SEQUENCE IF NOT EXISTS popup_products_id_seq;
CREATE TABLE IF NOT EXISTS popup_products (
  id           bigint NOT NULL DEFAULT nextval('popup_products_id_seq'),
  popup_id     bigint NOT NULL REFERENCES popup_events(id) ON DELETE CASCADE,
  no           integer,
  group_name   text,
  product_name text NOT NULL,
  option_name  text,
  price_krw    numeric,
  url          text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS popup_products_popup_idx ON popup_products (popup_id, no);
ALTER TABLE popup_products DROP CONSTRAINT IF EXISTS popup_products_popup_no_unq;
ALTER TABLE popup_products ADD CONSTRAINT popup_products_popup_no_unq UNIQUE (popup_id, no);

-- Functions
CREATE OR REPLACE FUNCTION public.go_campaign_status(p_deadline date, p_is_closed boolean)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE
    WHEN p_is_closed OR p_deadline IS NULL OR p_deadline < CURRENT_DATE THEN 'closed'
    WHEN p_deadline - CURRENT_DATE <= 3 THEN 'closing_soon'
    ELSE 'open'
  END;
$$;

CREATE OR REPLACE FUNCTION public.decrement_inventory_stock(
  p_sku text, p_qty integer, p_warehouse text DEFAULT 'kr'
)
RETURNS TABLE(
  matched boolean,
  inventory_id bigint,
  before_stock integer,
  after_stock integer,
  safety_stock integer,
  needs_reorder boolean
)
LANGUAGE plpgsql AS $$
DECLARE
  v_id BIGINT;
  v_before INTEGER;
  v_safety INTEGER;
  v_after INTEGER;
BEGIN
  IF p_warehouse = 'tw' THEN
    SELECT inv.id, inv.stock_tw, inv.safety_stock_tw
      INTO v_id, v_before, v_safety
      FROM inventory inv WHERE inv.id = (SELECT id FROM inventory WHERE location||idol||album||version||member = p_sku LIMIT 1);
  ELSE
    SELECT inv.id, inv.stock_kr, inv.safety_stock
      INTO v_id, v_before, v_safety
      FROM inventory inv WHERE inv.id = (SELECT id FROM inventory WHERE location||idol||album||version||member = p_sku LIMIT 1);
  END IF;
  IF v_id IS NULL THEN
    RETURN QUERY SELECT false, NULL::BIGINT, NULL::INTEGER, NULL::INTEGER, NULL::INTEGER, false;
    RETURN;
  END IF;
  v_after := GREATEST(v_before - p_qty, 0);
  IF p_warehouse = 'tw' THEN
    UPDATE inventory SET stock_tw = v_after, updated_at = now() WHERE id = v_id;
  ELSE
    UPDATE inventory SET stock_kr = v_after, updated_at = now() WHERE id = v_id;
  END IF;
  RETURN QUERY SELECT true, v_id, v_before, v_after, v_safety, (v_after <= COALESCE(v_safety, 0));
END;
$$;

-- View
CREATE OR REPLACE VIEW public.go_campaign_aggregate AS
SELECT
  c.go_code, c.category, c.idol_name, c.album, c.version,
  c.retail_store, c.deadline,
  go_campaign_status(c.deadline, c.is_closed) AS status,
  COALESCE(sum(CASE WHEN o.status = ANY (ARRAY['submitted','confirmed']) THEN i.qty ELSE 0 END), 0) AS total_qty,
  COALESCE(count(DISTINCT CASE WHEN o.status = ANY (ARRAY['submitted','confirmed']) THEN o.id ELSE NULL END), 0) AS buyer_count,
  COALESCE(sum(CASE WHEN o.status = ANY (ARRAY['submitted','confirmed']) THEN i.line_total_krw ELSE 0 END), 0) AS total_krw
FROM go_campaigns c
LEFT JOIN go_buyer_order_items i ON i.go_code = c.go_code
LEFT JOIN go_buyer_orders o ON o.id = i.order_id
GROUP BY c.id, c.go_code, c.category, c.idol_name, c.album, c.version,
         c.retail_store, c.deadline, c.is_closed;
